name: voo_terminal_example
description: Example app for VooTerminal package
publish_to: 'none'
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_terminal:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
